version: "3"
services:
  frontend:
    command: npm run dev
    environment:
      NODE_ENV: 'development'
    ports:
      - "1234:1234"
    volumes:
      - ../packages/frontend/src:/usr/src/app/packages/frontend/src
      - ../packages/frontend/public:/usr/src/app/packages/frontend/public
      - ../packages/shared:/usr/src/app/packages/shared
      - ./files:/files

  server:
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: 'development'
    volumes:
      - ../packages/server/src:/usr/src/app/packages/server/src
      - ../packages/shared:/usr/src/app/packages/shared
      - ./files:/files